name: Check packages

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check Packages
    strategy:
      matrix:
        package:
        - grimblast
        - shellevents
        - scratchpad
        - hyprprop
        - try_swap_workspace
        - hdrop
        - hyprosd-mako
        - cycle-layout

    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)
    uses: hyprwm/actions/.github/workflows/nix.yml@main
    secrets: inherit
    with:
      command: nix build -L .#${{ matrix.package }}
