name: Check scripts

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check scripts
    strategy:
      matrix:
        package:
        - "**/*.sh" # checks all .sh files
        - grimblast/grimblast
        - shellevents/shellevents
        - scratchpad/scratchpad
        - hyprprop/hyprprop
        - try_swap_workspace/try_swap_workspace
        - hdrop/hdrop
        - cycle-layout/cycle-layout

    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)
    uses: hyprwm/actions/.github/workflows/nix.yml@main
    secrets: inherit
    with:
      command: nix run nixpkgs#shellcheck -- -S error ${{ matrix.package }}
